path_planner:
  ros__parameters:
    max_velocity: 1.0
    max_acceleration: 0.5
    goal_tolerance: 0.1
    obstacle_distance: 0.5
    path_resolution: 0.1
    planner_type: "A*"
    replan_frequency: 1.0