# Created by Nelson Durrant, Oct 2024
services:
  byu-marsrover:
    image: byuawesomerover/byu-marsrover:latest
    container_name: byu-marsrover
    build: .
    user: marsrover
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=$DISPLAY # Required for GUI applications
      - QT_X11_NO_MITSHM=1 # Required for GUI applications
    volumes:
      - ../ros2_ws:/home/marsrover/ros2_ws
      - ../demo_ws:/home/marsrover/demo_ws
      - ./scripts:/home/marsrover/scripts
      - /etc/localtime:/etc/localtime:ro # Syncs the container's time with the host
      - /var/run/docker.sock:/var/run/docker.sock # Required for docker in docker
      - /tmp/.X11-unix:/tmp/.X11-unix # Required for GUI applications
      - /dev:/dev:rw
    stdin_open: true  # Equivalent to -it in docker run
    tty: true  # Equivalent to -it in docker run
    restart: always  # Optional: Keeps the container running after exit unless you want it to be removed like with --rm
    command: ["/bin/bash", "-c", "/home/marsrover/scripts/entrypoint.sh", "/bin/bash"]
