# Waypoints for the REAL WORLD environment
waypoints:

# GPS waypoints
# 1st waypoint (GPS only)
- leg: gps1
  latitude: 0.0
  longitude: 0.0
# 2nd waypoint (GPS only)
- leg: gps2
  latitude: 0.0
  longitude: 0.0

# Aruco tag waypoints
# 3rd waypoint (Aruco tag)
- leg: aruco1
  latitude: 0.0
  longitude: 0.0
# 4th waypoint (Aruco tag)
- leg: aruco2
  latitude: 0.0
  longitude: 0.0
# 5th waypoint (Aruco tag)
- leg: aruco3
  latitude: 0.0
  longitude: 0.0

# Object waypoints
# 6th waypoint (Mallet)
- leg: mallet
  latitude: 0.0
  longitude: 0.0
# 7th waypoint (Bottle)
- leg: bottle
  latitude: 0.0
  longitude: 0.0
