# Created by Nelson Durrant, Feb 2025

# Legs to perform in order
legs:
- leg: aruco1
- leg: gps1
- leg: mallet

# Aruco tags for the rover to detect
aruco_tags:
- leg: aruco1
  id: 0
- leg: aruco2
  id: 0
- leg: aruco3
  id: 0

# Waypoints for the rover to follow
waypoints:
# 1st waypoint (GPS only)
- leg: gps1
  latitude: 38.162923
  longitude: -122.454987
# 2nd waypoint (GPS only)
- leg: gps2
  latitude: 0.0
  longitude: 0.0
# 3rd waypoint (Aruco)
- leg: aruco1
  latitude: 38.162958
  longitude: -122.455412
# 4th waypoint (Aruco)
- leg: aruco2
  latitude: 0.0
  longitude: 0.0
# 5th waypoint (Aruco)
- leg: aruco3
  latitude: 0.0
  longitude: 0.0
# 6th waypoint (Mallet)
- leg: mallet
  latitude: 38.162633
  longitude: -122.454858
# 7th waypoint (Bottle)
- leg: bottle
  latitude: 0.0
  longitude: 0.0