/**:
  ros__parameters:
    locations:
      byu:
        latitude: 40.2497218
        longitude: -111.649276
        altitude: 1376.0
        heading: 0.0
      rock_canyon:
        latitude: 41.267147
        longitude: -111.632455
        altitude: 0.0
        heading: 0.0
      hanksville:
        latitude: 38.406441
        longitude: -110.791932
        altitude: 1375.0
        heading: 0.0
      gravel_pit:
        latitude: 40.322243
        longitude: -111.644278
        altitude: 1500.0
        heading: 0.0
      little_moab:
        latitude: 40.057020
        longitude: -112.012014
        altitude: 1500.0
        heading: 0.0
